 CREATE TABLE RECORDS (
  ACCOUNT_NUMBER BIGINT(20) NOT NULL,
  TYPE varchar(30),
  RECORD_DATE date NOT NULL,
  START_TIME TIME NOT NULL,
  END_TIME TIME NOT NULL,
  POWER_USAGE double(3,2),
  UNITS varchar(3),
  COST DOUBLE(4,2),
  NOTES varchar(100),
  PRIMARY KEY (ACCOUNT_NUMBER,RECORD_DATE,START_TIME,END_TIME)
);

 CREATE TABLE CLIENT (
  ACCOUNT_NUMBER BIGINT (20) NOT NULL,
  NAME varchar(60) NOT NULL,
  ADDRESS varchar(100) NOT NULL,
  SERVICE varchar(30) DEFAULT NULL,
  PRIMARY KEY (ACCOUNT_NUMBER)
);

CREATE TABLE USER(
USERNAME VARCHAR(100) NOT NULL, 
PASSWORD VARCHAR(55) NOT NULL, 
HINT VARCHAR(55) NOT NULL,
PRIMARY KEY (USERNAME)
);


CREATE TABLE ROLES(
	USERNAME VARCHAR(100) NOT NULL, 
	ROLE VARCHAR(50) NOT NULL
);

--Generate all URL links on the menu dynamicly based on 
CREATE TABLE NAVIGATION(
	NAV_ID INT(3) NOT NULL,
	NAV_NAME VARCHAR(100) NOT NULL, 
	NAV_PATH VARCHAR(200) NOT NULL, 
	NAV_PARENT_ID INT(3),
	ADMIN_ONLY VARCHAR(1) NOT NULL, 
	PRIMARY KEY(NAV_ID)
);

--ADD FORMAT?
CREATE TABLE GRID_META(
	COLUMN_META_ID INT(4) auto_increment,
	GRID_ID INT(3) NOT NULL, 
	COLUMN_NAME VARCHAR(100) NOT NULL, 
	COLUMN_LABEL VARCHAR(100) NOT NULL, 
	COLUMN_WIDTH INT(3) NOT NULL,
	TYPE VARCHAR(50) NOT NULL,
	PRIMARY KEY (COLUMN_META_ID)
);

--inserts for grid Metadata
INSERT INTO GRID_META(GRID_ID,COLUMN_NAME,COLUMN_LABEL,COLUMN_WIDTH,TYPE) VALUES(1, 'DATE','Record Date', 50, 'DATE');
INSERT INTO GRID_META(GRID_ID,COLUMN_NAME,COLUMN_LABEL,COLUMN_WIDTH,TYPE) VALUES(1, 'COST','Electric Cost', 100, 'DOLLAR');
INSERT INTO GRID_META(GRID_ID,COLUMN_NAME,COLUMN_LABEL,COLUMN_WIDTH,TYPE) VALUES(1, 'POWER_USAGE','Usage', 100,'NUMBER');

INSERT INTO GRID_META(GRID_ID,COLUMN_NAME,COLUMN_LABEL,COLUMN_WIDTH,TYPE) VALUES(1, 'MONTH','Month', 50, 'DATE_MONTH');
INSERT INTO GRID_META(GRID_ID,COLUMN_NAME,COLUMN_LABEL,COLUMN_WIDTH,TYPE) VALUES(1, 'YEAR','Year', 50, 'DATE_YEAR');
--inserts for user. 
INSERT INTO GRID_META(GRID_ID,COLUMN_NAME,COLUMN_LABEL,COLUMN_WIDTH,TYPE) VALUES(2, 'accountNumber','Account Number', 50, 'DATE');
INSERT INTO GRID_META(GRID_ID,COLUMN_NAME,COLUMN_LABEL,COLUMN_WIDTH,TYPE) VALUES(2, 'name','Client Name', 100, 'DOLLAR');
INSERT INTO GRID_META(GRID_ID,COLUMN_NAME,COLUMN_LABEL,COLUMN_WIDTH,TYPE) VALUES(2, 'address','Address', 100,'NUMBER');
INSERT INTO GRID_META(GRID_ID,COLUMN_NAME,COLUMN_LABEL,COLUMN_WIDTH,TYPE) VALUES(2, 'service','Service', 50, 'DATE_MONTH');




--SELECT STATEMENTS FOR VARIOUS QUERIES 
--Day seraches.  
SELECT RECORD_DATE, sum(COST), sum(POWER_USAGE) FROM POWER_INFO 
WHERE ACCOUNT_NUMBER = ? 
GROUP BY RECORD_DATE;
SELECT YEAR(RECORD_DATE) AS YEAR, MONTH(RECORD_DATE) AS MONTH, SUM(COST) FROM POWER_INFO
WHERE ACCOUNT_NUMBER = ?
GROUP BY MONTH(RECORD_DATE), YEAR(RECORD_DATE);



SELECT YEAR(RECORD_DATE) AS YEAR, MONTH(RECORD_DATE) AS MONTH, SUM(COST) FROM POWER_INFO GROUP BY MONTH(RECORD_DATE), YEAR(RECORD_DATE);



-------------------------------
SELECT DATE_FORMAT(RECORD_DATE,'%Y%m') as DATE, SUM(COST) AS COST, SUM(POWER_USAGE) AS POWER_USAGE
FROM POWER_INFO 
WHERE ACCOUNT_NUMBER = ?
GROUP BY DATE ;
